### ISSUE TITLE
Error deploying/need help with deploying

### ISSUE THREAD

**Issue by davidm5375** [smakosh/covid-19-next#14]
When trying tl deploy, it failed due to a dependency issue(???) i believe. Also what would be the best place to deploy it to?

**Comment by davidm5375** [comment]
ID 1a4fba47-26f7-4338-9747-7ee5a8b185aa
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.16.1...
       Using default npm version: 6.13.4
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > ejs@2.7.4 postinstall /tmp/build_246c5898cdac21815caaf84ae4fb2cc2/node_modules/ejs
       > node ./postinstall.js
       
       
       > styled-components@4.4.1 postinstall /tmp/build_246c5898cdac21815caaf84ae4fb2cc2/node_modules/react-flex-ready/node_modules/styled-components
       > node ./scripts/postinstall.js || exit 0
       
       Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
       added 1109 packages from 573 contributors and audited 11711 packages in 26.345s
       
       18 packages are looking for funding
         run `npm fund` for details
       
       found 11 vulnerabilities (1 low, 8 moderate, 2 high)
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build
       Running build
       
       > corona-ssg@0.1.0 build /tmp/build_246c5898cdac21815caaf84ae4fb2cc2
       > next build
       
       Creating an optimized production build...
       Attention: Next.js now collects completely anonymous telemetry regarding usage.
       This information is used to shape Next.js' roadmap and prioritize features.
       You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
       https://nextjs.org/telemetry
       
       > [PWA] Compile client (static)
       > [PWA] Auto register service worker with: /tmp/build_246c5898cdac21815caaf84ae4fb2cc2/node_modules/next-pwa/register.js
       > [PWA] Service worker: /tmp/build_246c5898cdac21815caaf84ae4fb2cc2/public/sw.js
       > [PWA]   url: /sw.js
       > [PWA]   scope: /
       > [PWA] Compile server
       > Using external babel configuration
       > Location: "/tmp/build_246c5898cdac21815caaf84ae4fb2cc2/.babelrc"
       
       Compiled successfully.
       
       Automatically optimizing pages...
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`.
Read more: https://err.sh/next.js/opt-out-auto-static-optimization
Error occurred prerendering page "/XK". Read more: https://err.sh/next.js/prerender-error:
TypeError: Cannot read property 'emoji' of undefined
> Build error occurred
Error: Export encountered errors
    at _default (/tmp/build_246c5898cdac21815caaf84ae4fb2cc2/node_modules/next/dist/export/index.js:19:811)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (/tmp/build_246c5898cdac21815caaf84ae4fb2cc2/node_modules/next/dist/build/index.js:34:218)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! corona-ssg@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the corona-ssg@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.ne32x/_logs/2020-03-31T05_34_16_827Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
Build finished
heroku.com
Blogs
Careers
Documentation
Support
Terms of Service
Privacy
Cookies

**Comment by smakosh** [comment]
That API is not really stable, it keeps changing over time, if you have some other API, please link it in the comments

**Comment by smakosh** [comment]
It has been fixed
