### ISSUE TITLE
Avoid scrolling on mobile

### ISSUE THREAD

**Issue by OKinane** [smakosh/covid-19-next#2]
Number details are taking too much space on my mobile screen. In fact I should not have to scroll at all.

**Comment by smakosh** [comment]
Tried my best, let me know what you think

**Comment by OKinane** [comment]
Is the new version deployed? I see no change.

**Comment by smakosh** [comment]
Since it's a PWA and I didn't handle updating SW when new update is available, you will have to clear your storage cache

**Comment by redaelkhayat** [comment]
This needs styling enhancements ! not a big deal @smakosh
